[package]
name = "rust-ownership"
version = "0.1.0"
authors = ["Bruno Giovagnoli <bruno.giovagnoli@snagajob.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
